import Head from "next/head";

export default function Home() {
  return (
    <div className="flex">
      <Head>
        <title>NextJS + TailwindCSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center w-full mt-10 font-bold text-slate-900">Hello World</h1>
    </div>
  );
}
